### ISSUE TITLE
created_at search

### ISSUE THREAD

**Issue by JoshMcKin** [appoxy/simple_record#10]
Its been my observation that searching by "created_at" does not return results. However, searching by "created" does return results. Should the readme be changed/updated or am I doing something wrong?

puts Log.find(:all, :conditions => ["created >  ?", 3.days.ago]).length 
  => 25

puts Log.find(:all, :conditions => ["created_at >  ?", 3.days.ago]).length 
 => 0

Thanks,

Josh

**Comment by appoxy** [comment]
Hi Josh,

You are correct, the README is wrong. Just changed it and thanks for the heads up.

**Comment by JoshMcKin** [comment]
No problem.
I saw that "created_at" was just "created" aliased, but was not sure if there was some string magic going behind the scenes.

Thanks
Josh
