### ISSUE TITLE
Add some info to Getting Started

### ISSUE THREAD

**Issue by AlexGM** [appoxy/simple_record#14]
The author did great work, but some people (like me) will save a lot of time knowing that simple_record DO support Consistent Read and multiple attribute values (returning them as array).

**Comment by appoxy** [comment]
Added consistent read not, but we don't fully support multi attribute values since it's not supported on save yet.

**Comment by AlexGM** [comment]
Thank you! Will look forward for multiple values save - this is one of most interesting features for projects initially aimed to use SimpleDB.
I working on such project and will be great to use full SimpleDB potential.
One step ahead...
