### ISSUE TITLE
simple_record-1.5.7 causing:  Aws::AwsError: InvalidNextToken: The specified next token is not valid.

### ISSUE THREAD

**Issue by JoshMcKin** [appoxy/simple_record#15]
Updated to 1.5.7 but receive the following error when I try a get request:

Aws::AwsError: InvalidNextToken: The specified next token is not valid.
REQUEST=sdb.amazonaws.com:443/?AWSAccessKeyId=CHANGEDRF6UVPI3XSHQA&Action=Select&NextToken=%7B%7D&SelectExpression=SELECT%20%2A%20FROM%20%60sit_pay_accounts%60&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2010-12-03T14%3A39%3A51.000Z&Version=2009-04-15&Signature=CHANGED5HXuAgcLmWveypSAsphzxecKK3faors%2B0%3D

(I added the CHANGED to the signaure and keyid)

Works just fine in simple_record-1.4.19.

Did something change that requires a change in my model from 1.4.19 to 1.5.7?

**Comment by appoxy** [comment]
Any chance you have the backtrace for this?  I may have broken this yesterday.

**Comment by appoxy** [comment]
Also, can you verify that you have 2.3.27 of aws gem?

**Comment by JoshMcKin** [comment]
Updating the AWS gem fix it.

Thanks,

**Comment by appoxy** [comment]
cool
