### ISSUE TITLE
Add support for standard Rails validations (in at least Rails 3)

### ISSUE THREAD

**Issue by kevinrood** [appoxy/simple_record#16]
Writing a test app and noticed that the standard Rails validator "validates_presence_of" or "validates :presence => true" does not work.  This was a Rails 3 app.

**Comment by treeder** [comment]
Hey Kevin,

This should be supported now along with other ActiveModel validations. If not, ask and I'll reopen.

**Comment by kevinrood** [comment]
Thanks @treeder
