### ISSUE TITLE
has_virtuals is not working

### ISSUE THREAD

**Issue by jmclachlan** [appoxy/simple_record#35]
The values are just empty after initialization. No error is thrown.

**Comment by treeder** [comment]
I think I fixed it assuming the following is the issue:

```
model = MyBaseModel.new(:v1=>'abc', :base_string=>'what')
assert model.v1 == 'abc', "model.v1=" + model.v1.inspect
```

Where v1 is a virtual. This used to fail, but now passes.

**Comment by jmclachlan** [comment]
Yep. This looks good. Thanks!
