### ISSUE TITLE
cleaning up the 'puts'

### ISSUE THREAD

**Issue by daniel-nelson** [appoxy/simple_record#40]
Would you be open to a pull request that removes puts statements, or that creates a class setting whereby putting can be disabled? '3 update' and '3 create' are making my tests run ugly.

**Comment by treeder** [comment]
Definitely. Even better would be if you could turn them into logger.debug
statements (unless they are just cruft, then just remove them).

**Comment by daniel-nelson** [comment]
Thank you; however, I just discovered the [aws-sdk gem](https://github.com/amazonwebservices/aws-sdk-for-ruby), released by Amazon. It includes AWS::Record that looks really nice. I think I'm switching over to that.
