### ISSUE TITLE
has_many doesn't contain foreign key

### ISSUE THREAD

**Issue by superjustin** [appoxy/simple_record#48]

**Comment by superjustin** [comment]
pull request is committed in master

**Comment by pr1001** [comment]
Does this work now? I have the following code:

```
has_many    :albums, :foreign_key => 'albumId'
```

When I try to load the model I get:

```
TypeError: {:foreign_key=>"albumId"} is not a symbol
```

I'm using simple_record 2.2.0

**Comment by superjustin** [comment]
Hi Peter, 

I added a class relationship.  Use the :class_name instead. 

Here's an example:
models/invite.rb:   belongs_to :invitee, :class_name => 'User'
models/user.rb:    has_one  :invitee, :class_name => 'Invite'

-------- Original Message --------
Subject: Re: [simple_record] has_many doesn't contain foreign key (#48)
From: Peter Robinett
reply@reply.github.com
Date: Fri, July 27, 2012 3:18 am
To: Justin Mui jmui@phatsite.com
Does this work now? I have the following code:
    has_many    :albums, :foreign_key => 'albumId'
When I try to load the model I get:
    TypeError: {:foreign_key=>"albumId"} is not a symbol

## I'm using simple_record 2.2.0

**Comment by pr1001** [comment]
Ok, thanks. Since simple_record assumes `modelname_id`, I rolled my own method:

```
def album
  Album.find(albumId)
end
```

**Comment by superjustin** [comment]
Yes, class_name will use modelname_id
