### ISSUE TITLE
delete needs to delete objects from s3 (clobs, etc)

### ISSUE THREAD

**Issue by appoxy** [appoxy/simple_record#5]
Right now it only deletes from SimpleDB so the s3 objects are left orphaned.

**Comment by catwell** [comment]
Same as [issue 4](http://github.com/appoxy/simple_record/issues#issue/4), I did that [here](http://github.com/Moodstocks/ar-simpledb/blob/master/lib/simple_record/simplerecord.rb), although it's only on destroy and not delete (see delete_lobs).

**Comment by appoxy** [comment]
done.
