### ISSUE TITLE
Lots of wrong tests

### ISSUE THREAD

**Issue by catwell** [appoxy/simple_record#6]
In the current test suite lots of tests don't do what they are supposed to because of syntax errors, for instance in [test_simple_record.rb](http://github.com/appoxy/simple_record/blob/master/test/test_simple_record.rb):

```
    assert mm2.cool = true
    assert mm2.name = "Travis"
```

You should probably use assert_equal instead to avoid this kind of problems.

**Comment by appoxy** [comment]
Thanks for heads up. Went through and found some of these. Let me know if there are more.
